### ISSUE TITLE
Support for Wemos Mini D1

### ISSUE THREAD

**Issue by anthonyjclarke** [neptune2/esp8266-weather-station-color-DST#1]
Hope this is the correct way to question (n00B)

Taken squix working version, and left connections the same, compile and upload your code and just get blank white screen.  To fix I had to update 👍 

#define TFT_DC 2
#define TFT_CS 5

Second, is seems its display issue, any suggestions?

Also get these warnings on MAC Arduino IDE 1.6.12

Volumes/Macintosh HD 2/Users/Documents/Arduino/esp8266-weather-station-color-DST/esp8266-weather-station-color-DST.ino: In function 'void configModeCallback(WiFiManager*)':
/Volumes/Macintosh HD 2/Users/Documents/Arduino/esp8266-weather-station-color-DST/esp8266-weather-station-color-DST.ino:180:40: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   ui.drawString(120, 28, "Wifi Manager");
                                        ^
/Volumes/Macintosh HD 2/Users/Documents/Arduino/esp8266-weather-station-color-DST/esp8266-weather-station-color-DST.ino:181:48: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   ui.drawString(120, 42, "Please connect to AP");
                                                ^
/Volumes/Macintosh HD 2/Users/Documents/Arduino/esp8266-weather-station-color-DST/esp8266-weather-station-color-DST.ino:185:55: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   ui.drawString(120, 70, "To setup Wifi Configuration");
                                                       ^
/Volumes/Macintosh HD 2/Users/Documents/Arduino/esp8266-weather-station-color-DST/esp8266-weather-station-color-DST.ino: In function 'void drawAstronomy()':
/Volumes/Macintosh HD 2/Users/Documents/Arduino/esp8266-weather-station-color-DST/esp8266-weather-station-color-DST.ino:381:31: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   ui.drawString(20, 270, "Sun");
                               ^
/Volumes/Macintosh HD 2/Users/Documents/Arduino/esp8266-weather-station-color-DST/esp8266-weather-station-color-DST.ino:388:33: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
   ui.drawString(220, 270, "Moon");

**Comment by neptune2** [comment]
Hi Anthony - this is a good question.
It points out a deficiency in my documentation and settings.h comments.

The original Squix78 version uses a NodeMCU ESP8266 board, but I am using the Wemos D1 R2. There are some confusing and subtle differences in the way that the pins are numbered in settings.h

The change you made in settings.h is the correct change needed to use the NodeMCU setup as described in the original Squix78 https://github.com/squix78/esp8266-weather-station-color

The following table shows the the differences:

## Code Differences

| ILI9341 | Original Squix78 settings.h | Neptune2 settings.h |
| --- | :-: | :-: |
| DC/RS | #define TFT_DC 2 | #define TFT_DC D3 |
| CS | #define TFT_CS 5 | #define TFT_CS D2 |

### NodeMCU:

![nodeMCU](http://www.14core.com/wp-content/uploads/2015/06/Node-MCU-Pin-Out-Diagram1.png)

### Wemos D1-mini:

![wemos D1-mini](https://esp8266.ru/forum/attachments/d1-mini-esp8266-pinout-jpg.1541/)

### Wemos D1R2:

![Wemos D1R2](http://geekelectronics.org/wp-content/uploads/2016/01/image-32.png)

### re: MAC compile errors:

I do not see the errors when compiling on a MAC.
I did a fresh install of Arduino IDE 1.6.12 and all ESP8266 board framework and libraries on MAC OSX 10.11.6 (El Capitan). I did not get any errors. 

**Do you have the latest ESP8266 framework and libraries needed by the weather-station-color ?**
