### ISSUE TITLE
Change clock Colour

### ISSUE THREAD

**Issue by aceycv8** [neptune2/esp8266-weather-station-color-DST#5]
This is probably something simple - but what are the codes to change the colour of the clock?
e.g. from green to white?
i assume its #define ILI9341_CLOCKGREEN 0x7FE5
#define ILI9341_SILHOUTTEGREEN 0x0280
but i dont know the codes for the colour

**Comment by Andrew252010** [comment]
#define ILI9341_CLOCKGREEN 0xFFFF
#define ILI9341_SILHOUTTEGREEN 0x39E7
http://www.barth-dev.de/online/rgb565-color-picker/

**Comment by aceycv8** [comment]
well that is embarrassing

thank you!
